acct = accounts.load('LQDogDeployer')
"""
Addresses Definitions
"""
BURN_ADDRESS = '0x1234567890123456789012345678901234567890'
RESERVE_ADDRESS= '0x99B687e58Bb7cb9000c502Dd62f58910BC7f8592'
LIQUIDITYDOG_ADDRESS = '0x721Fa74C94830f0Cb93C8Ec2D80fd2099EDA8AD3'
reserve_contract = Contract.from_abi("Reserve",
                                     RESERVE_ADDRESS,
                                     [{"inputs":[{"internalType":"address","name":"_spookyswapRouter","type":"address"},{"internalType":"address","name":"_usdcAddress","type":"address"}],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":False,"inputs":[{"indexed":False,"internalType":"uint256","name":"amountSHQ","type":"uint256"},{"indexed":False,"internalType":"uint256","name":"amountUSDC","type":"uint256"}],"name":"ShqBought","type":"event"},{"anonymous":False,"inputs":[{"indexed":False,"internalType":"uint256","name":"amountSHQ","type":"uint256"},{"indexed":False,"internalType":"uint256","name":"amountUSDC","type":"uint256"}],"name":"ShqSold","type":"event"},{"inputs":[{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"addToShqToConvert","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"buyPrice","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"buyPriceWithTax","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"_beneficiary","type":"address"},{"internalType":"uint256","name":"_shqAmount","type":"uint256"}],"name":"buyShq","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"_beneficiary","type":"address"},{"internalType":"uint256","name":"_usdcAmount","type":"uint256"}],"name":"buyShqWithUsdc","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"distributor","outputs":[{"internalType":"contract HolderRewarderDistributor","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"sellPrice","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"_beneficiary","type":"address"},{"internalType":"uint256","name":"_shqAmount","type":"uint256"}],"name":"sellShq","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"_addr","type":"address"}],"name":"setSheqelTokenAddress","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_taxRate","type":"uint256"}],"name":"setTaxRate","outputs":[],"stateMutability":"nonpayable","type":"function"}])

